repos:
  - repo: git://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-ast
      - id: fix-encoding-pragma
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        args:
          - --max-line-length=130
  - repo: git://github.com/pre-commit/mirrors-eslint
    rev: v7.13.0-1
    hooks:
      - id: eslint
  - repo: git://github.com/pre-commit/mirrors-scss-lint
    rev: v0.59.0
    hooks:
      - id: scss-lint
