repos:
  - repo: git://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: git://github.com/ambv/black
    rev: 22.1.0
    hooks:
      - id: black
        language_version: python3
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-ast
      - id: fix-encoding-pragma
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args:
          - --max-line-length=130
  - repo: git://github.com/pre-commit/mirrors-eslint
    rev: v8.11.0
    hooks:
      - id: eslint
  - repo: git://github.com/pre-commit/mirrors-scss-lint
    rev: v0.59.0
    hooks:
      - id: scss-lint
