repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-ast
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args:
          - --max-line-length=130
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.13.0
    hooks:
      - id: eslint
  - repo: https://github.com/pre-commit/mirrors-scss-lint
    rev: v0.59.0
    hooks:
      - id: scss-lint
