repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    -   id: black
        language_version: python3
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    -   id: check-merge-conflict
    -   id: trailing-whitespace
    -   id: check-symlinks
    -   id: end-of-file-fixer
    -   id: debug-statements
    -   id: check-ast
    -   id: fix-encoding-pragma
    -   id: flake8
        args:
        - --max-line-length=130
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v6.3.0
    hooks:
    -   id: eslint
-   repo: https://github.com/pre-commit/mirrors-scss-lint
    rev: v0.58.0
    hooks:
    -   id: scss-lint
