version: "3"
services:
  db:
    image: "postgres:14"
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - db/.env
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    networks:
      - db_network

  backend:
    build: backend
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - backend/.env
    networks:
      - db_network
    volumes:
      - "backenddata:/data/backend:ro"
      - "./staticfiles:/home/user/backend/staticfiles"
    depends_on:
      - db

  backoffice:
    build: backend
    env_file:
      - backend/.env
    networks:
      - db_network
    volumes:
      - "backenddata:/data/backend"
    depends_on:
      - db
    command: python manage.py runscheduler

networks:
  db_network:
    driver: bridge
volumes:
  dbdata:
  backenddata:
