version: "3"
services:
  db:
    image: "postgres:14"
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - db/.env
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    networks:
      - db_network

  backend:
    build:
      context: backend
      args:
        UID: $UID
        GID: $GID
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - db_network
    volumes:
      - "backenddata:/data/backend:ro"
      - "./backend/staticfiles:/home/user/backend/staticfiles"
    depends_on:
      - db

  backoffice:
    build:
      context: backend
      args:
        UID: $UID
        GID: $GID
    networks:
      - db_network
    volumes:
      - "backenddata:/data/backend"
    depends_on:
      - db
    command: python manage.py runscheduler

networks:
  db_network:
    driver: bridge
volumes:
  dbdata:
  backenddata:
