version: '3'
services:
  backend:
    build: backend
    env_file:
      - backend/.env.local
    networks:
      - web_network
    volumes:
      - "backenddata:/data/backend:ro"

  backoffice:
    build: backend
    env_file:
      - backend/.env.local
    volumes:
      - "backenddata:/data/backend"
    command: ../backoffice

  nginx:
    image: "nginx:1.15"
    ports:
      - "127.0.0.1:10080:80"
    volumes:
      - ./nginx/conf.d/backend.conf:/etc/nginx/conf.d/backend.conf
    networks:
      - web_network
    depends_on:
      - backend

networks:
  web_network:
    driver: bridge
volumes:
  backenddata:
