version: '3'
services:

  db:
    image: "mongo:4.4"
    ports:
      - "127.0.0.1:27017:27017"
    env_file:
      - db/.env.local
    volumes:
      - "dbdata:/data/db"
    networks:
      - db_network

  backend:
    build: backend
    env_file:
      - backend/.env.local
    networks:
      - db_network
      - web_network
    volumes:
      - "backenddata:/data/backend:ro"
    depends_on:
      - db

  backoffice:
    build: backend
    env_file:
      - backend/.env.local
    networks:
      - db_network
    volumes:
      - "backenddata:/data/backend"
    depends_on:
      - db
    command: ./backoffice

  nginx:
    image: "nginx:1"
    ports:
      - "127.0.0.1:10080:80"
    volumes:
      - ./nginx/conf.d/backend.conf:/etc/nginx/conf.d/backend.conf
    networks:
      - web_network
    depends_on:
      - backend

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
volumes:
  dbdata:
  backenddata:
