version: '3'
services:

  db:
    image: "mongo:4"
    volumes:
    - "dbdata:/data/db"
    networks:
    - db_network

  backend:
    build: backend
    env_file:
    - backend/.env.${ENVIRONMENT:-production}
    networks:
    - db_network
    - web_network
    depends_on:
    - db

  backoffice:
    build: backend
    env_file:
    - backend/.env.${ENVIRONMENT:-production}
    volumes:
    - "shareddata:/data/shared"
    networks:
    - db_network
    depends_on:
    - db
    command: ../backoffice

  frontend:
    build: frontend
    env_file:
    - frontend/.env.${ENVIRONMENT:-production}
    volumes:
    - "shareddata:/data/shared"
    networks:
    - web_network
    depends_on:
    - backend

  nginx:
    image: "nginx:1"
    ports:
    - "127.0.0.1:10080:80"
    volumes:
    - ./nginx/conf.d/backend.conf:/etc/nginx/conf.d/backend.conf
    - ./nginx/conf.d/frontend.conf:/etc/nginx/conf.d/frontend.conf
    networks:
    - web_network
    depends_on:
    - backend
    - frontend

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
volumes:
  dbdata:
  shareddata:
