version: '3'
services:

  db:
    image: "postgres:14"
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - db/.env
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    networks:
      - db_network

  backend:
    build: backend
    env_file:
      - backend/.env
    networks:
      - db_network
      - web_network
    volumes:
      - "backenddata:/data/backend:ro"
    depends_on:
      - db

  backoffice:
    build: backend
    env_file:
      - backend/.env
    networks:
      - db_network
    volumes:
      - "backenddata:/data/backend"
    depends_on:
      - db
    command: python manage.py runscheduler

  nginx:
    image: "nginx:1"
    ports:
      - "127.0.0.1:10080:80"
    volumes:
      - ./nginx/conf.d/backend.conf:/etc/nginx/conf.d/backend.conf
    networks:
      - web_network
    depends_on:
      - backend

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
volumes:
  dbdata:
  backenddata:
